/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Diego Álvarez
 */
public class comprarCasas extends javax.swing.JFrame {
    MonopolyJF refPantalla;
    /**
     * Creates new form NewJFrame
     */
    public comprarCasas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void updateCombo(ArrayList <String> props){
        System.out.println("Combo listas");
        cProps.removeAllItems();
        for(int i = 0; i < props.size(); i++){
            cProps.addItem(props.get(i));
        }
    }
    public void updateData(int c, int h){
        System.out.println("Casas: "+c+" Hoteles: "+h);
        cantCasas.setText(c+"");
        cantHotel.setText(h+"");
        System.out.println("Casas listas");
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cantCasas = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        vender = new javax.swing.JButton();
        comprar = new javax.swing.JButton();
        cProps = new javax.swing.JComboBox<>();
        cant = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cantHotel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cantCasas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cantCasas.setText("0");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Casas/hotel.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Casas/casa.png"))); // NOI18N

        vender.setText("Vender Casa");
        vender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venderActionPerformed(evt);
            }
        });

        comprar.setText("Comprar Casa");
        comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarActionPerformed(evt);
            }
        });

        cProps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cPropsActionPerformed(evt);
            }
        });

        cant.setText("0");

        jLabel3.setText("Cantidad casas: ");

        cantHotel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cantHotel.setText("0");

        jLabel4.setText("Precio por casa: ");

        precio.setText("0");

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cProps, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vender)
                            .addComponent(comprar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(precio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cant))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantCasas, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cantCasas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cantHotel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(cProps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cant))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(precio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(comprar)
                .addGap(18, 18, 18)
                .addComponent(vender)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void venderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venderActionPerformed
              try {
            refPantalla.refCliente.hiloCliente.writer.writeInt(34);
            refPantalla.refCliente.hiloCliente.writer.writeInt(cProps.getSelectedIndex());
        } catch (IOException ex) {
            Logger.getLogger(comprarCasas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_venderActionPerformed
    public void actualizarCompra() throws IOException{
        refPantalla.refCliente.hiloCliente.writer.writeInt(32);
       int selected = cProps.getSelectedIndex();
        try {
            if (selected > -1){
            refPantalla.refCliente.hiloCliente.writer.writeInt(33);
            refPantalla.refCliente.hiloCliente.writer.writeInt(selected);
            }
                    } catch (IOException ex) {
            Logger.getLogger(comprarCasas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarActionPerformed
        try {
            refPantalla.refCliente.hiloCliente.writer.writeInt(35);
            refPantalla.refCliente.hiloCliente.writer.writeInt(cProps.getSelectedIndex());
        } catch (IOException ex) {
            Logger.getLogger(comprarCasas.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_comprarActionPerformed
    private void updateButtons(int c, int p, int d, boolean b) {
        System.out.println(b);
        if(b){
            if (d >= p && c < 5){
                comprar.setEnabled(true);
            }
            else{
                comprar.setEnabled(false);
            }
            if(c == 0){
                vender.setEnabled(false);
            }
            else{
                vender.setEnabled(true);
            }
        }
        else{
            comprar.setEnabled(false);
            vender.setEnabled(false);
        }
    }
    public void opcionValida(int casas, int precio, int dinero, boolean can){
        System.out.println("Opcion valida");
        cant.setText(casas+"");
        this.precio.setText(precio+"");
        updateButtons(casas, precio, dinero, can);
    }
    public void opcionInvalida(){
        System.out.println("Opcion invalida");
        cant.setText("");
        this.precio.setText("");
        comprar.setEnabled(false);
        vender.setEnabled(false);
    }
    private void cPropsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cPropsActionPerformed
        int selected = cProps.getSelectedIndex();
        System.out.println("Selected: "+selected);
        try {
            if (selected == -1)
                    selected = 0;
            refPantalla.refCliente.hiloCliente.writer.writeInt(33);
            refPantalla.refCliente.hiloCliente.writer.writeInt(selected);
                    } catch (IOException ex) {
            Logger.getLogger(comprarCasas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cPropsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(comprarCasas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(comprarCasas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(comprarCasas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(comprarCasas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new comprarCasas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cProps;
    private javax.swing.JLabel cant;
    private javax.swing.JLabel cantCasas;
    private javax.swing.JLabel cantHotel;
    private javax.swing.JButton comprar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel precio;
    private javax.swing.JButton vender;
    // End of variables declaration//GEN-END:variables


}
