/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;


import java.awt.event.KeyEvent;
import java.io.IOException;
import static java.lang.Boolean.parseBoolean;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Alejandra G
 */
public class MonopolyJF extends javax.swing.JFrame {

    /**
     * Creates new form MonopolyJF
     */
    public boolean actualizado = false;
    public ArrayList<String> botones;
    public ArrayList<String> nombres;
    ArrayList<JLabel> lblAL;
    Cliente refCliente;
    private String nombreTurno = "";
    public String nickname = "";
    public String pieza = "hello";
    public MonopolyJF() {
        initComponents();
        lblAL = new ArrayList();
        JLabel lblToken1 = new javax.swing.JLabel();
        JLabel lblToken2 = new javax.swing.JLabel();
        JLabel lblToken3 = new javax.swing.JLabel();
        JLabel lblToken4 = new javax.swing.JLabel();
        JLabel lblToken5 = new javax.swing.JLabel();
        JLabel lblToken6 = new javax.swing.JLabel();
        lblAL.add(lblToken1);
        lblAL.add(lblToken2);
        lblAL.add(lblToken3);
        lblAL.add(lblToken4);
        lblAL.add(lblToken5);
        lblAL.add(lblToken6);

    }

    public void setRefCliente(Cliente refCliente) {
        this.refCliente = refCliente;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inicio = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnIntercambiar = new javax.swing.JButton();
        btnHipotecar = new javax.swing.JButton();
        btnConstruir = new javax.swing.JButton();
        btnTerminarTurno = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cbbNombres = new javax.swing.JComboBox<>();
        lblMoney = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lblProperties = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTextArea19 = new javax.swing.JTextArea();
        jLabel34 = new javax.swing.JLabel();
        chatSms = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblDado2 = new javax.swing.JLabel();
        lblDado1 = new javax.swing.JLabel();
        btnLanzarDados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inicio.setOpaque(false);
        inicio.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 600, 90, 90));

        jPanel1.setBackground(new java.awt.Color(206, 255, 221));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIntercambiar.setBackground(new java.awt.Color(121, 150, 130));
        btnIntercambiar.setForeground(new java.awt.Color(255, 255, 255));
        btnIntercambiar.setText("INTERCAMBIAR");
        btnIntercambiar.setEnabled(false);
        btnIntercambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntercambiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIntercambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 50));

        btnHipotecar.setBackground(new java.awt.Color(121, 150, 130));
        btnHipotecar.setForeground(new java.awt.Color(255, 255, 255));
        btnHipotecar.setText("HIPOTECAR");
        btnHipotecar.setEnabled(false);
        btnHipotecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHipotecarActionPerformed(evt);
            }
        });
        jPanel1.add(btnHipotecar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 110, 50));

        btnConstruir.setBackground(new java.awt.Color(121, 150, 130));
        btnConstruir.setForeground(new java.awt.Color(255, 255, 255));
        btnConstruir.setText("CONSTRUIR");
        btnConstruir.setEnabled(false);
        btnConstruir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConstruirActionPerformed(evt);
            }
        });
        jPanel1.add(btnConstruir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 110, 50));

        btnTerminarTurno.setBackground(new java.awt.Color(121, 150, 130));
        btnTerminarTurno.setForeground(new java.awt.Color(255, 255, 255));
        btnTerminarTurno.setText("TERMINAR TURNO");
        btnTerminarTurno.setEnabled(false);
        btnTerminarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarTurnoActionPerformed(evt);
            }
        });
        jPanel1.add(btnTerminarTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 130, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 540, 550, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Tablero.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 690));

        jPanel3.setBackground(new java.awt.Color(206, 255, 221));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbbNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNombresActionPerformed(evt);
            }
        });
        jPanel3.add(cbbNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 140, 20));

        lblMoney.setBackground(new java.awt.Color(255, 255, 255));
        lblMoney.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMoney.setOpaque(true);
        jPanel3.add(lblMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 170, 20));

        lblProperties.setColumns(20);
        lblProperties.setRows(5);
        jScrollPane3.setViewportView(lblProperties);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 300, 100));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Jugador:");
        jLabel10.setOpaque(true);
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 20));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Propiedades:");
        jLabel8.setOpaque(true);
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, 20));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Dinero:");
        jLabel11.setOpaque(true);
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 330, 250));

        jPanel19.setBackground(new java.awt.Color(206, 255, 221));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea19.setColumns(20);
        jTextArea19.setRows(5);
        jScrollPane19.setViewportView(jTextArea19);

        jPanel19.add(jScrollPane19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 300, 180));

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("CHAT");
        jLabel34.setOpaque(true);
        jPanel19.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 20));

        chatSms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatSmsActionPerformed(evt);
            }
        });
        chatSms.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                chatSmsKeyPressed(evt);
            }
        });
        jPanel19.add(chatSms, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 300, -1));

        getContentPane().add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 330, 270));

        jPanel2.setBackground(new java.awt.Color(206, 255, 221));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDado2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblDado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 84, 84));

        lblDado1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(lblDado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 84, 84));

        btnLanzarDados.setBackground(new java.awt.Color(121, 150, 130));
        btnLanzarDados.setForeground(new java.awt.Color(255, 255, 255));
        btnLanzarDados.setText("LANZAR DADOS");
        btnLanzarDados.setEnabled(false);
        btnLanzarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanzarDadosActionPerformed(evt);
            }
        });
        jPanel2.add(btnLanzarDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 110, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, 210, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setTitulo(){
        this.setTitle(refCliente.nickname);
    }
    private void cbbNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNombresActionPerformed
        try {
            // TODO add your handling code here:
            int index = cbbNombres.getSelectedIndex();
            if(index>-1 && actualizado){
            refCliente.hiloCliente.writer.writeInt(6);
            refCliente.hiloCliente.writer.writeInt(index);
            }
        } catch (IOException ex) {
            Logger.getLogger(MonopolyJF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbbNombresActionPerformed

    private void chatSmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatSmsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chatSmsActionPerformed

    private void btnIntercambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntercambiarActionPerformed


    }//GEN-LAST:event_btnIntercambiarActionPerformed

    private void btnLanzarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanzarDadosActionPerformed
        // TODO add your handling code here:
        try {
            refCliente.hiloCliente.writer.writeInt(6);
            } catch (IOException ex) {
            Logger.getLogger(MonopolyJF.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_btnLanzarDadosActionPerformed
    public void addMessage(String msj){
        jTextArea19.append(msj + "\n");
    }
    public void pintarLanzamientoDados(String icon1,String icon2,String iguales){
        lblDado1.setIcon(new javax.swing.ImageIcon(getClass().getResource(icon1))); // NOI18
        lblDado2.setIcon(new javax.swing.ImageIcon(getClass().getResource(icon2)));
        if (!parseBoolean(iguales)){
            btnLanzarDados.setEnabled(false);
        }
    }
    public void habilitarBtns(){
        btnLanzarDados.setEnabled(true);
        btnIntercambiar.setEnabled(true);
        btnHipotecar.setEnabled(true);
        btnConstruir.setEnabled(true);
        btnTerminarTurno.setEnabled(true);
    }
    public void deshabilitarBtns(){
        btnLanzarDados.setEnabled(false);
        btnIntercambiar.setEnabled(false);
        btnHipotecar.setEnabled(false);
        btnConstruir.setEnabled(false);
        btnTerminarTurno.setEnabled(false);
    }
    private void chatSmsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chatSmsKeyPressed
        // TODO add your handling code here:
      if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
          try {
              String str = chatSms.getText();
              refCliente.hiloCliente.writer.writeInt(5);
              refCliente.hiloCliente.writer.writeUTF(str);
              chatSms.setText("");
          } catch (IOException ex) {
              Logger.getLogger(MonopolyJF.class.getName()).log(Level.SEVERE, null, ex);
          }
   }
    }//GEN-LAST:event_chatSmsKeyPressed

    private void btnHipotecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHipotecarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHipotecarActionPerformed

    private void btnConstruirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConstruirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConstruirActionPerformed

    private void btnTerminarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarTurnoActionPerformed
        // TODO add your handling code here:
        try {
              refCliente.hiloCliente.writer.writeInt(7);
          } catch (IOException ex) {
              Logger.getLogger(MonopolyJF.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_btnTerminarTurnoActionPerformed
    public void actualizarCBBplayer(String propiedades,String dinero){
        lblMoney.setText("");
        lblProperties.setText("");
        lblMoney.setText(dinero);
        lblProperties.setText(propiedades);
    }
    public void actualizarCBB(){
        for (int i = 0; i < nombres.size(); i++){
            cbbNombres.addItem(nombres.get(i));
        } 
        cbbNombres.setSelectedIndex(-1);
        actualizado = true;
    }
    public void colocarBtnsInicio(){
        for (int i = 0; i < botones.size(); i++) {
            lblAL.get(i).setSize(32, 32);
            lblAL.get(i).setIcon(new javax.swing.ImageIcon(getClass().getResource(botones.get(i)))); // NOI18N
            lblAL.get(i).setOpaque(false);
            inicio.add(lblAL.get(i));   
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonopolyJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonopolyJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonopolyJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonopolyJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonopolyJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConstruir;
    private javax.swing.JButton btnHipotecar;
    private javax.swing.JButton btnIntercambiar;
    private javax.swing.JButton btnLanzarDados;
    private javax.swing.JButton btnTerminarTurno;
    private javax.swing.JComboBox<String> cbbNombres;
    private javax.swing.JTextField chatSms;
    private javax.swing.JPanel inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea19;
    private javax.swing.JLabel lblDado1;
    private javax.swing.JLabel lblDado2;
    private javax.swing.JLabel lblMoney;
    private javax.swing.JTextArea lblProperties;
    // End of variables declaration//GEN-END:variables


}
