/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;

import java.io.IOException;
import static java.lang.Boolean.parseBoolean;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Alejandra G
 */
public class PropiedadesJF extends javax.swing.JFrame {
    MonopolyJF pantallaPrincipal;
    String imagen;
    int plataPagar = 0;
    int plataActual = 0;
    BrokeForm ventanaQuiebra;
    /**
     * Creates new form PropiedadesJF
     */
    public PropiedadesJF() {
        
        initComponents();
        ventanaQuiebra = new BrokeForm();
        ventanaQuiebra.refPantalla = this;
        panelDisponible.setVisible(false);
        panelNoDisponible.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblProperty = new javax.swing.JLabel();
        panelDisponible = new javax.swing.JPanel();
        btnComprar = new javax.swing.JButton();
        btnSubastar = new javax.swing.JButton();
        panelNoDisponible = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblDueño = new javax.swing.JLabel();
        lblPagar = new javax.swing.JLabel();
        lblMoney = new javax.swing.JLabel();
        btnPagar = new javax.swing.JButton();
        pnlUtility = new javax.swing.JPanel();
        lblGG = new javax.swing.JLabel();
        lblDado1 = new javax.swing.JLabel();
        lblDado2 = new javax.swing.JLabel();
        btnLanzarDados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Ha caido en:");

        btnComprar.setText("COMPRAR");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        btnSubastar.setText("SUBASTAR");
        btnSubastar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubastarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDisponibleLayout = new javax.swing.GroupLayout(panelDisponible);
        panelDisponible.setLayout(panelDisponibleLayout);
        panelDisponibleLayout.setHorizontalGroup(
            panelDisponibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDisponibleLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnSubastar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        panelDisponibleLayout.setVerticalGroup(
            panelDisponibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDisponibleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDisponibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComprar, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(btnSubastar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Del dueño:");

        lblDueño.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblPagar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblMoney.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnPagar.setText("PAGAR");
        btnPagar.setEnabled(false);
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        lblGG.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGG.setText("Lance los dados para calcular el precio a pagar:");

        lblDado1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDado2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnLanzarDados.setBackground(new java.awt.Color(121, 150, 130));
        btnLanzarDados.setForeground(new java.awt.Color(255, 255, 255));
        btnLanzarDados.setText("LANZAR DADOS");
        btnLanzarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanzarDadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUtilityLayout = new javax.swing.GroupLayout(pnlUtility);
        pnlUtility.setLayout(pnlUtilityLayout);
        pnlUtilityLayout.setHorizontalGroup(
            pnlUtilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUtilityLayout.createSequentialGroup()
                .addGroup(pnlUtilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUtilityLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblGG, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUtilityLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblDado1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(lblDado2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLanzarDados)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        pnlUtilityLayout.setVerticalGroup(
            pnlUtilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUtilityLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGG, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlUtilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlUtilityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblDado1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDado2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLanzarDados))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelNoDisponibleLayout = new javax.swing.GroupLayout(panelNoDisponible);
        panelNoDisponible.setLayout(panelNoDisponibleLayout);
        panelNoDisponibleLayout.setHorizontalGroup(
            panelNoDisponibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNoDisponibleLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelNoDisponibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(178, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNoDisponibleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelNoDisponibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNoDisponibleLayout.createSequentialGroup()
                        .addComponent(lblDueño, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNoDisponibleLayout.createSequentialGroup()
                        .addComponent(btnPagar)
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNoDisponibleLayout.createSequentialGroup()
                        .addComponent(pnlUtility, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
            .addGroup(panelNoDisponibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelNoDisponibleLayout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jLabel5)
                    .addContainerGap(348, Short.MAX_VALUE)))
        );
        panelNoDisponibleLayout.setVerticalGroup(
            panelNoDisponibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNoDisponibleLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblDueño, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlUtility, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(lblPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPagar)
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(panelNoDisponibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelNoDisponibleLayout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jLabel5)
                    .addContainerGap(323, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProperty, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelNoDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(316, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(lblProperty, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(panelDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(panelNoDisponible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(158, 158, 158))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(504, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        try {
            // TODO add your handling code here:
            pantallaPrincipal.refCliente.hiloCliente.writer.writeInt(10);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(PropiedadesJF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnComprarActionPerformed
    public void actualizarJFDinero(int dinero){
        this.plataActual = dinero;
        lblMoney.setText("Saldo actual: "+ plataActual);
        if(plataActual >= plataPagar)
            btnPagar.setEnabled(true);
     
    }
    public void actualizarDineroActual(){
        try {
            // TODO add your handling code here:
            pantallaPrincipal.refCliente.hiloCliente.writer.writeInt(10);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(PropiedadesJF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnSubastarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubastarActionPerformed
        System.out.println("Hi :(");
        try {
            pantallaPrincipal.refCliente.hiloCliente.writer.writeInt(11);   
            //System.out.println(imagen);// TODO add your handling code here:
            pantallaPrincipal.refCliente.hiloCliente.writer.writeUTF(imagen);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(PropiedadesJF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSubastarActionPerformed
    public void pintarLanzamientoDados(String icon1,String icon2,int plataActual,int plataPagar) throws IOException{
        lblDado1.setIcon(new javax.swing.ImageIcon(getClass().getResource(icon1))); // NOI18
        lblDado2.setIcon(new javax.swing.ImageIcon(getClass().getResource(icon2)));
        btnLanzarDados.setEnabled(false);
        this.plataActual = plataActual;
        this.plataPagar = plataPagar;
        lblPagar.setText("Debe pagar: "+ plataPagar);
        lblMoney.setText("Saldo actual: "+ plataActual);
        if(plataActual >= plataPagar)
            btnPagar.setEnabled(true);
        else {
            ventanaQuiebra.setVisible(true);
        }
    }
    public void pintarDatos(int plataActual,int plataPagar) throws IOException{
        this.plataActual = plataActual;
        this.plataPagar = plataPagar;
        lblPagar.setText("Debe pagar: "+ plataPagar);
        lblMoney.setText("Saldo actual: "+ plataActual);
        if(plataActual >= plataPagar)
            btnPagar.setEnabled(true);
        else {
            ventanaQuiebra.setVisible(true);
        }
    }
    private void btnLanzarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanzarDadosActionPerformed
        // TODO add your handling code here:
        try {
            pantallaPrincipal.refCliente.hiloCliente.writer.writeInt(23);
            pantallaPrincipal.refCliente.hiloCliente.writer.writeInt(0);
        } catch (IOException ex) {
            Logger.getLogger(MonopolyJF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLanzarDadosActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        // TODO add your handling code here:
        try {
            pantallaPrincipal.refCliente.hiloCliente.writer.writeInt(24);
            pantallaPrincipal.refCliente.hiloCliente.writer.writeInt(plataPagar);
            JOptionPane.showMessageDialog(this, "Ha pagado, su saldo actual es de: "+(plataActual-plataPagar));
            pnlUtility.setVisible(false);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(MonopolyJF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public void mostrarPropDisponible(String url){
        this.imagen = url;
        lblProperty.setIcon( new ImageIcon(getClass().getResource(url)));
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PropiedadesJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PropiedadesJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PropiedadesJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PropiedadesJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PropiedadesJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnLanzarDados;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnSubastar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblDado1;
    private javax.swing.JLabel lblDado2;
    public javax.swing.JLabel lblDueño;
    public javax.swing.JLabel lblGG;
    public javax.swing.JLabel lblMoney;
    public javax.swing.JLabel lblPagar;
    public javax.swing.JLabel lblProperty;
    public javax.swing.JPanel panelDisponible;
    public javax.swing.JPanel panelNoDisponible;
    public javax.swing.JPanel pnlUtility;
    // End of variables declaration//GEN-END:variables
}
