/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JSpinner;
import javax.swing.JTextArea;

/**
 *
 * @author Diego Álvarez
 */
public class ventanaIntercambio extends javax.swing.JFrame {
    MonopolyJF refPantalla;
    ArrayList<String> propiedadesSolicitadas;
    ArrayList<String> propiedadesOfrecidas;
    int dineroSolicitado;
    int dineroOfrecido;
    int otroJugador;

    /**
     * Creates new form NewJFrame
     */
    public ventanaIntercambio() {
        initComponents();
        propiedadesSolicitadas = new ArrayList<String>();
        propiedadesOfrecidas = new ArrayList<String>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        nombre1 = new javax.swing.JLabel();
        misPropiedades = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        SpinnerDinero = new javax.swing.JSpinner();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaPropiedades = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        dineroPropio = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ofrecerProp = new javax.swing.JButton();
        ofrecerDinero = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        nombre2 = new javax.swing.JLabel();
        susPropiedades = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        SpinnerDineroAjeno = new javax.swing.JSpinner();
        jScrollPane5 = new javax.swing.JScrollPane();
        listaPropiedadesAjenas = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        dineroAjeno = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        solicitarProp = new javax.swing.JButton();
        solicitarDinero = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        aceptar = new javax.swing.JButton();
        nueva = new javax.swing.JButton();
        rechazar = new javax.swing.JButton();
        reinicir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel6.setBackground(new java.awt.Color(153, 255, 153));

        nombre1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nombre1.setText("Persona 1");

        misPropiedades.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                misPropiedadesFocusGained(evt);
            }
        });
        misPropiedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                misPropiedadesActionPerformed(evt);
            }
        });
        misPropiedades.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                misPropiedadesPropertyChange(evt);
            }
        });

        jLabel13.setText("Propiedades Disponibles: ");

        jLabel14.setText("Dinero:");

        listaPropiedades.setEditable(false);
        listaPropiedades.setColumns(20);
        listaPropiedades.setRows(5);
        jScrollPane4.setViewportView(listaPropiedades);

        jLabel15.setText("Propiedades Ofertadas: ");

        dineroPropio.setEditable(false);
        dineroPropio.setText("0 $");
        dineroPropio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dineroPropioActionPerformed(evt);
            }
        });

        jLabel16.setText("Dinero Ofertado:");

        ofrecerProp.setText("Ofrecer Propiedad");
        ofrecerProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ofrecerPropActionPerformed(evt);
            }
        });

        ofrecerDinero.setText("Ofrecer Dinero");
        ofrecerDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ofrecerDineroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SpinnerDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(misPropiedades, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(dineroPropio, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ofrecerProp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ofrecerDinero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 49, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane4))))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(nombre1)
                .addGap(27, 27, 27)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(misPropiedades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SpinnerDinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(ofrecerProp)
                        .addGap(18, 18, 18)
                        .addComponent(ofrecerDinero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dineroPropio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(153, 255, 153));

        nombre2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nombre2.setText("Persona 2");

        susPropiedades.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                susPropiedadesFocusGained(evt);
            }
        });
        susPropiedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                susPropiedadesActionPerformed(evt);
            }
        });

        jLabel17.setText("Propiedades Disponibles: ");

        jLabel18.setText("Dinero:");

        listaPropiedadesAjenas.setEditable(false);
        listaPropiedadesAjenas.setColumns(20);
        listaPropiedadesAjenas.setRows(5);
        jScrollPane5.setViewportView(listaPropiedadesAjenas);

        jLabel19.setText("Propiedades Ofertadas: ");

        dineroAjeno.setEditable(false);
        dineroAjeno.setText("0 $");
        dineroAjeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dineroAjenoActionPerformed(evt);
            }
        });

        jLabel20.setText("Dinero Ofertado:");

        solicitarProp.setText("Solicitar Propiedad");
        solicitarProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitarPropActionPerformed(evt);
            }
        });

        solicitarDinero.setText("Solicitar Dinero");
        solicitarDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitarDineroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52))
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(susPropiedades, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(SpinnerDineroAjeno, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(dineroAjeno, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(solicitarDinero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(solicitarProp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(67, 67, 67)))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane5)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(nombre2)
                .addGap(27, 27, 27)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(susPropiedades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SpinnerDineroAjeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(solicitarProp)
                        .addGap(18, 18, 18)
                        .addComponent(solicitarDinero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dineroAjeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        jPanel2.add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 22, 143, 67));

        nueva.setText("Nueva oferta");
        nueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaActionPerformed(evt);
            }
        });
        jPanel2.add(nueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 22, 143, 67));

        rechazar.setText("Rechazar");
        rechazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechazarActionPerformed(evt);
            }
        });
        jPanel2.add(rechazar, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 22, 143, 67));

        reinicir.setText("Reiniciar ofera");
        reinicir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reinicirActionPerformed(evt);
            }
        });
        jPanel2.add(reinicir, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 22, 143, 67));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 937, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void mostrarSolicitud(ArrayList<String> meOfrece, ArrayList<String> mePide, int dinOfrece, int dinPide){
        aceptar.setEnabled(true);
        propiedadesSolicitadas = meOfrece;
        propiedadesOfrecidas = mePide;
        actualizarTextField(meOfrece,listaPropiedadesAjenas);
        actualizarTextField(mePide,listaPropiedades);
        dineroOfrecido= dinPide;
        dineroPropio.setText(dineroOfrecido+" $");
        dineroSolicitado = dinOfrece;
        dineroAjeno.setText(dineroSolicitado+" $");
    }
    private void dineroPropioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dineroPropioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dineroPropioActionPerformed

    private void ofrecerDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ofrecerDineroActionPerformed
       aceptar.setEnabled(false);
       dineroOfrecido= (int) SpinnerDinero.getValue();
       dineroPropio.setText(dineroOfrecido+" $");
    }//GEN-LAST:event_ofrecerDineroActionPerformed

    private void dineroAjenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dineroAjenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dineroAjenoActionPerformed
    private boolean isIn(ArrayList<String> names,JComboBox combo){
        System.out.println("Algo");
        for(int i = 0; i<names.size();i++){
            System.out.println("Está: "+names.get(i));
            if(names.get(i).equals(combo.getSelectedItem().toString())){
                System.out.println("Sí");
                return true;
            }
        }
        return false;
    }
    private void solicitarPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitarPropActionPerformed
        aceptar.setEnabled(false);
        if (!isIn(propiedadesSolicitadas,susPropiedades)){
            propiedadesSolicitadas.add(susPropiedades.getSelectedItem().toString());
            actualizarTextField(propiedadesSolicitadas,listaPropiedadesAjenas);
        }   
    }//GEN-LAST:event_solicitarPropActionPerformed

    private void solicitarDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitarDineroActionPerformed
       aceptar.setEnabled(false);
       dineroSolicitado = (int) SpinnerDineroAjeno.getValue();
       dineroAjeno.setText(dineroSolicitado+" $");
    }//GEN-LAST:event_solicitarDineroActionPerformed
    private void sendAll() throws IOException{
            refPantalla.refCliente.hiloCliente.writer.writeInt(otroJugador);
            refPantalla.refCliente.hiloCliente.objWriter.writeObject(propiedadesOfrecidas);
            refPantalla.refCliente.hiloCliente.objWriter.writeObject(propiedadesSolicitadas);
            refPantalla.refCliente.hiloCliente.writer.writeInt(dineroOfrecido);
            refPantalla.refCliente.hiloCliente.writer.writeInt(dineroSolicitado);
    }
    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        try {
            refPantalla.refCliente.hiloCliente.writer.writeInt(22);
            sendAll();
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(ventanaIntercambio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_aceptarActionPerformed

    private void nuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaActionPerformed
        try {
            refPantalla.refCliente.hiloCliente.writer.writeInt(20);
            sendAll();
            this.setVisible(false);
            
        } catch (IOException ex) {
            Logger.getLogger(ventanaIntercambio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nuevaActionPerformed

    private void rechazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechazarActionPerformed
        borrarTodo();
        try {
            System.out.println("Borremos todo alv");
            this.setVisible(false);
            refPantalla.refCliente.hiloCliente.writer.writeInt(21);
            refPantalla.refCliente.hiloCliente.writer.writeInt(otroJugador);
            
        } catch (IOException ex) {
            Logger.getLogger(ventanaIntercambio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_rechazarActionPerformed

    private void actualizarTextField(ArrayList<String> names,JTextArea area){
        String resultado= "";
        for(int i = 0; i<names.size();i++){
            resultado += names.get(i)+"\n";
        }
        area.setText(resultado);
    }
    private void ofrecerPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ofrecerPropActionPerformed
        aceptar.setEnabled(false);
        if (!isIn(propiedadesOfrecidas,misPropiedades)){
            propiedadesOfrecidas.add(misPropiedades.getSelectedItem().toString());
            actualizarTextField(propiedadesOfrecidas,listaPropiedades);
        }   
    }//GEN-LAST:event_ofrecerPropActionPerformed

    private void misPropiedadesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_misPropiedadesPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_misPropiedadesPropertyChange

    private void misPropiedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_misPropiedadesActionPerformed

    }//GEN-LAST:event_misPropiedadesActionPerformed

    private void susPropiedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_susPropiedadesActionPerformed


    }//GEN-LAST:event_susPropiedadesActionPerformed

    private void misPropiedadesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_misPropiedadesFocusGained

    }//GEN-LAST:event_misPropiedadesFocusGained

    private void susPropiedadesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_susPropiedadesFocusGained
        
  
    }//GEN-LAST:event_susPropiedadesFocusGained
    private void borrarTodo(){
        aceptar.setEnabled(false);
        propiedadesOfrecidas.clear();
        propiedadesSolicitadas.clear();
        dineroSolicitado = 0;
        dineroOfrecido = 0;
        listaPropiedades.setText("");
        listaPropiedadesAjenas.setText("");
        dineroPropio.setText("0 $");
        dineroAjeno.setText("0 $");
    }
    private void reinicirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reinicirActionPerformed
        aceptar.setEnabled(false);
        propiedadesOfrecidas.clear();
        propiedadesSolicitadas.clear();
        dineroSolicitado = 0;
        dineroOfrecido = 0;
        listaPropiedades.setText("");
        listaPropiedadesAjenas.setText("");
        dineroPropio.setText("0 $");
        dineroAjeno.setText("0 $");
    }//GEN-LAST:event_reinicirActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaIntercambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaIntercambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaIntercambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaIntercambio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaIntercambio().setVisible(true);
            }
        });
    }
    public void updateComboBoxes(ArrayList<String> props,JComboBox combo){
        combo.removeAllItems();
        for(int i = 0; i<props.size();i++){
            combo.addItem(props.get(i));
            System.out.println("Estoy enclicado");
        }
    }
    public void updateSpinners(int max,JSpinner spin){
        spin.setModel(new javax.swing.SpinnerNumberModel(0, 0, max, 1));
    }
    public void updateData(ArrayList<String> props1,ArrayList<String> props2,int dinero1,int dinero2,String nombre2,int otraPersona){
        otroJugador = otraPersona;
        this.setTitle(nombre2);
        updateComboBoxes(props1,misPropiedades);
        updateComboBoxes(props2,susPropiedades);
        System.out.println("Al final no estaba encliclado");
        updateSpinners(dinero1,SpinnerDinero);
        updateSpinners(dinero2,SpinnerDineroAjeno);
        System.out.println("Spinners Listos");
        this.nombre1.setText(refPantalla.refCliente.nickname);
        this.nombre2.setText(nombre2);
        System.out.println("Todo listo");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SpinnerDinero;
    private javax.swing.JSpinner SpinnerDineroAjeno;
    public javax.swing.JButton aceptar;
    private javax.swing.JTextField dineroAjeno;
    private javax.swing.JTextField dineroPropio;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea listaPropiedades;
    private javax.swing.JTextArea listaPropiedadesAjenas;
    private javax.swing.JComboBox<String> misPropiedades;
    private javax.swing.JLabel nombre1;
    private javax.swing.JLabel nombre2;
    private javax.swing.JButton nueva;
    private javax.swing.JButton ofrecerDinero;
    private javax.swing.JButton ofrecerProp;
    private javax.swing.JButton rechazar;
    private javax.swing.JButton reinicir;
    private javax.swing.JButton solicitarDinero;
    private javax.swing.JButton solicitarProp;
    private javax.swing.JComboBox<String> susPropiedades;
    // End of variables declaration//GEN-END:variables
}
